### ISSUE TITLE
Graphical glitches on Ultimate Shuttle IVA [bug}

### ISSUE THREAD

**Issue by TheSystemGuy1337** [StoneBlue/ASET-Consolidated-Avionics#4]
You're not gonna care, but I'm gonna complain anyway. ASET Consolidated causes graphical glitches on the switches in the Ultimate Shuttle IVA, see screenshots: 
![screenshot0](https://github.com/StoneBlue/ASET-Consolidated-Avionics/assets/61162037/b486bc87-e090-4cd1-a64c-292f4fb23ed5)
![screenshot1](https://github.com/StoneBlue/ASET-Consolidated-Avionics/assets/61162037/517ac3c4-3b08-4a77-9d6a-738ed2431386)

**Comment by JonnyOThan** [comment]
Pretty sure this is RPM’s fault not ASET

**Comment by TheSystemGuy1337** [comment]
Then where can I obtain a version of RPM circa 2018?On Jun 25, 2023, at 10:07 PM, JonnyOThan ***@***.***> wrote:﻿
Pretty sure this is RPM’s fault not ASET

**Comment by TheSystemGuy1337** [comment]
Downgraded and the issue vanished.
